### ISSUE TITLE
Request: put information in text file and attach it to the email

### ISSUE THREAD

**Issue by eclair4151** [schayes04/SupportEmail#18] opened 2017-12-08 14:18 UTC
I would like to request the feature where all this info is put inside a debug text file and attached to the email. Some of the time i have a lot of info to add and long session tokens ect that i don't want the end user to be confused by in their email.

**Comment by schayes04** [comment] 2017-12-10 21:40
Duplicate of #10

**Closed as completed** 2017-12-10 21:41 UTC

**Comment by schayes04** [comment] 2017-12-11 00:54
Added in release 2.1.0!
